server:
  port: 8080

spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://localhost:5432/notification_db
    username: postgres
    password: plutoski12       # ← change this to your actual postgres password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: a4ee26001@smtp-brevo.com
    password: YWLDc6vFbBm8yK5f
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

notification:
  email:
    from: jumaa.gunda101@gmail.com
    from-name: Notification Service